services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: lab2
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - "./исходные данные:/csv:ro"
      - ./postgres-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d lab2" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  spark:
    image: jupyter/pyspark-notebook:latest
    container_name: spark
    hostname: spark
    environment:
      SPARK_HOME: /usr/local/spark
      PYTHONPATH: /usr/local/spark/python:/usr/local/spark/python/lib/py4j-0.10.9.7-src.zip:/usr/local/spark/python/lib/pyspark.zip
      PYSPARK_PYTHON: /opt/conda/bin/python
      SPARK_LOCAL_HOSTNAME: spark
      SPARK_LOCAL_IP: 127.0.0.1
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./jobs:/home/jovyan/work

  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    container_name: clickhouse
    environment:
      CLICKHOUSE_DB: lab2
      CLICKHOUSE_USER: user
      CLICKHOUSE_PASSWORD: password
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8123/ping | grep -q Ok." ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: lab2-cluster
      CASSANDRA_DC: datacenter1
      CASSANDRA_RACK: rack1
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 128M
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: [ "CMD-SHELL", "cqlsh -e 'DESCRIBE KEYSPACES' || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 20
    restart: unless-stopped

volumes:
  clickhouse_data:
  cassandra_data:
